manifest.xml: fix IMapper incompatible build error
Like the error report by the build here:
    https://ci.android.com/builds/submitted/9155358/beagle_x15-userdebug/latest/view/logs/build_error.log

    ERROR: files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 4. Manifest level = 4. The following requirements are not met:
    android.hardware.graphics.mapper:
        required:
            @2.1::IMapper/default OR
            @3.0::IMapper/default OR
            @4.0::IMapper/default
        provided: @2.0::IMapper/default

    android.hardware.graphics.mapper@2.0::IMapper/default is deprecated; requires at least 2.1: Success
    INCOMPATIBLE

Test: make droid & make dist
Fixes: 60d5b19d4017 ("manifest.xml: update FCM Version to 4 for API LEVEL 29")

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: Ifbf017727c4557029baee70b92d9c9f0e9462d84