BoardConfig.mk: set value for TARGET_BOOTLOADER_BOARD_NAME
so that there will be value for ro.product.board property,
and fix the vts execution problem like this:

    01-30 16:29:38 E/VtsMultiDeviceTest: Device 0e005017394200e2 not available.
    01-30 16:29:38 E/GranularRetriableTestWrapper: Module 'armeabi-v7a VtsKernelLtp' - test 'class com.android.tradefed.testtype.VtsMultiDeviceTest' threw exception:
    01-30 16:29:38 E/GranularRetriableTestWrapper: Failed to get device information
    java.lang.RuntimeException: Failed to get device information
        at com.android.tradefed.testtype.VtsMultiDeviceTest.generateJsonDeviceItem(VtsMultiDeviceTest.java:674)
        at com.android.tradefed.testtype.VtsMultiDeviceTest.updateVtsRunnerTestConfig(VtsMultiDeviceTest.java:830)
        at com.android.tradefed.testtype.VtsMultiDeviceTest.doRunTest(VtsMultiDeviceTest.java:1280)
        at com.android.tradefed.testtype.VtsMultiDeviceTest.run(VtsMultiDeviceTest.java:728)
        at com.android.tradefed.testtype.suite.GranularRetriableTestWrapper.intraModuleRun(GranularRetriableTestWrapper.java:396)
        at com.android.tradefed.testtype.suite.GranularRetriableTestWrapper.run(GranularRetriableTestWrapper.java:221)
        at com.android.tradefed.testtype.suite.ModuleDefinition.run(ModuleDefinition.java:462)
        at com.android.tradefed.testtype.suite.ITestSuite.runSingleModule(ITestSuite.java:606)
        at com.android.tradefed.testtype.suite.ITestSuite.run(ITestSuite.java:533)
        at com.android.tradefed.invoker.InvocationExecution.runTests(InvocationExecution.java:454)
        at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:367)
        at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:220)
        at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:724)
        at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:586)

    01-30 16:29:38 E/GranularRetriableTestWrapper: Proceeding to the next test.

Test: ./vts-tradefed run vts-kernel -m VtsKernelLtp

Change-Id: Iee108df1c389e0f014ffc05d14d16cc05d8ca412
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>